### PR TITLE
Make type case-insensitive

### PR DESCRIPTION
**Pull request by shreyasminocha**

### CODE REVIEW

**Comment by vadimdemedes** [comment]
Sorry, I don't think this would be a good change, I prefer strict options and values over loose input.

**Comment by shreyasminocha** [comment]
How about, say, accepting the global `Boolean` instead of `'boolean'`?

**Comment by vadimdemedes** [comment]
Why?

**Comment by shreyasminocha** [comment]
Because IMO it's more intuitive, but I'll take that to be a "no".

**Pull request closed without merging**
